language: node_js
node_js:
    - "0.10"
    - "0.12"
    - '4.*'
    - '5.*'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq beanstalkd
    - sudo beanstalkd -d -l 127.0.0.1 -p 11300
script: npm run travis
after_success: npm run coverage
